### ISSUE TITLE
Dockerized CHEUI

### ISSUE THREAD

**Issue by joegeorgeson** [comprna/CHEUI#12]
Dear CHEUI,

Any chance you have created a docker, or could create one?

Thanks

**Comment by Akanksha2511** [comment]
Thanks. We have not yet created a docker. But, thanks for the suggestion we will have one soon.

**Comment by joegeorgeson** [comment]
I saw this marked as completed, is there a docker now?

**Comment by pre-mRNA** [comment]
Hi, we're no longer planning on dockerizing CHEUI, but we can help you set it up if you'd like to run it on your cluster. 
Have you tried the conda-based installation suggested in the README?
