### ISSUE TITLE
add temp directory for preprocessing

### ISSUE THREAD

**Issue by joegeorgeson** [comprna/CHEUI#13]
Dear CHEUI,

Can you add an optional flag for your preprocessing script that allows designation of a temporary directory for writing temporary files that is separate from the final output directory? This is with clusters and/or cloud computing in mind, and/or users that have multiple discs at their disposal.

Thanks

**Comment by eileen-xue** [comment]
Hi,

This is now available at CHEUI preprocessing (C++ version).

Regards,
Eileen

**Comment by joegeorgeson** [comment]
So fast, thank you!
