### ISSUE TITLE
error while loading shared libraries: PicklingTools/libptools

### ISSUE THREAD

**Issue by xiangruhuo** [comprna/CHEUI#15]
Hi,
  When I use C++ version run the training, it gave me the error as this: 
error while loading shared libraries: PicklingTools/libptools.so: cannot open shared object file: No such file or directory
How should I solve that?

Thanks,
Xiangru

**Comment by xiangruhuo** [comment]
My command is as below:
~/CHEUI/scripts/preprocessing_CPP/CHEUI -i gDNA_CHEUI.reads.eventalign.txt -o gDNA_A_signals+IDs.p/ -m ~/CHEUI/kmer_models/model_kmer.csv -n 16 --m6A

Thanks,
Xiangru

**Comment by eileen-xue** [comment]
Hi Xiangru，

Did you meet any errors when using `./build.sh` command to install the C++ program? 

Which gcc version and operating system are you using?

Thanks,
Eileen

**Comment by xiangruhuo** [comment]
Hi Eileen,

I re-ran "./build.sh" again, and it seems give me a report like that : 
make: 'libptools.so' is up to date.
make: Nothing to be done for 'all'.
Following is the gcc version in linux: " gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-16)" 

Thanks,
Xiangru

> Hi Xiangru，
> 
> Did you meet any errors when using `./build.sh` command to install the C++ program?
> 
> Which gcc version and operating system are you using?
> 
> Thanks, Eileen

**Comment by eileen-xue** [comment]
Hi Xiangru,

Using `~/CHEUI/scripts/preprocessing_CPP/CHEUI`  in your command will meet this file path issue.

You can try `cd ~/CHEUI/scripts/preprocessing_CPP/` and run the program with `./CHEUI` command.

I hope this helps.

Thanks,
Eileen
