### ISSUE TITLE
too much predicted m6a modification site

### ISSUE THREAD

**Issue by baishengjun** [comprna/CHEUI#18]
Hi,

I predicted around 150000 m6a modification site using CHEUI, and using the probability cut-off of 0.8, but it should be range from 20000 to 50000 modification site. It seems too much, is there any some parameters to adjust when I predicted?

Thanks,
Bai

**Comment by EduEyras** [comment]
Hi,

I assume you are referring to CHEUI-solo Model 2 probability? That is, the
probability per transcriptomic site (as opposed to the probability per read
site).

We generally use 0.99 or 0.9999. The choice of 0.9999 was based on an
empirical estimation of the FDR in cell line data (scripts available in the
github).

Please let me know if this helps
best

E.

**Comment by baishengjun** [comment]
Hi,

Sorry for late reply, because it does not completely done. 
We obtained the 39226 m6a modification site and 12967 m5c modification site by using the probability cut-off of 0.99.
It seems good in the aspect of number of modification site.
I will compare the cheui results with m6anet results, and compare with the known modification site from databaes.

Thanks a lot
Bai
