### ISSUE TITLE
about reference transcriptome file and explanation of cheui output

### ISSUE THREAD

**Issue by rezarahman12** [comprna/CHEUI#20]
Hello CHEUI team,
Thank you so much for developing this wonderful software for the concurrent detection of m6A and m5C modification from nanopore dRNA-Seq. I'm running CHEUI on our in-house dRNA-seq data. I've got a few questions regarding the choice of reference transcriptome file and about the output file of CHEUI for site-level predictions.

1. I've used the UCSC mouse transcriptome reference file - "mRNA.fa" (https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/) and then aligned using minimap2. I'm just wondering about the Ensemble cDNA FASTA file "Mus_musculus.GRCm39.cdna.all.fa.gz"(https://ftp.ensembl.org/pub/release-109/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz) are also transcriptome reference file can be used for minimap2 transcriptome mapping? Are there any relative benefits of using Ensemble over the UCSC reference file?
2. I've attached below the site-level m6A predictions by CHEUI. The contig is UCSC transcript ID, how can I change this to gene symbol or ensemble gene ID? In the output file, I see only contig and position. What does this mean? Is there any way of getting the chrosome as well in the output file? 
3. What is the well-acceptable threshold to identify a significant m6A-modified site based on probability and stoichiometry?
I beg pardon as some questions are not relevant to CHEUI. 

I would appreciate your time and help. 

Kind regards
Reza
PhD Candidate at Queensland Brain Institute, The University of Queensland.

![image](https://github.com/comprna/CHEUI/assets/110575883/c51d6c11-f385-44de-a8ba-f8195a4ea603)

**Comment by EduEyras** [comment]
Hi Reza,

On Sat, 1 Jul 2023 at 13:45, rezarahman12 ***@***.***> wrote:

> Hello CHEUI team,
> Thank you so much for developing this wonderful software for the
> concurrent detection of m6A and m5C modification from nanopore dRNA-Seq.
> I'm running CHEUI on our in-house dRNA-seq data. I've got a few questions
> regarding the choice of reference transcriptome file and about the output
> file of CHEUI for site-level predictions.
>
thanks for your message and for using CHEUI

>
>    1. I've used the UCSC mouse transcriptome reference file - "mRNA.fa" (
>    https://hgdownload.soe.ucsc.edu/goldenPath/mm10/bigZips/) and then
>    aligned using minimap2. I'm just wondering about the Ensemble cDNA FASTA
>    file "Mus_musculus.GRCm39.cdna.all.fa.gz"(
>    https://ftp.ensembl.org/pub/release-109/fasta/mus_musculus/cdna/Mus_musculus.GRCm39.cdna.all.fa.gz)
>    are also transcriptome reference file can be used for minimap2
>    transcriptome mapping? Are there any relative benefits of using Ensemble
>    over the UCSC reference file?
>
> You can use any transcriptome reference you prefer.

One possible advantage of using Ensembl over UCSC transcriptome is that
Ensembl might be better annotated: with genes and alternative transcripts,
each with some functional annotation if available, etc.. The UCSC
annotation seems to be: *mrna.fa.gz - Mouse mRNA from GenBank.* This
is quite comprehensive, but may not be annotated in the same structured
way.

Also, Ensembl IDs are usually linked to a genome locus, whereas some of the
GenBank IDs (e.g. RefSeq IDs) refer to an mRNA molecule, not to a locus, so
you may see some ambiguities like the same RefSeq ID in two loci, unless
you use a locus ID from GenBank

>
>    1. I've attached below the site-level m6A predictions by CHEUI. The
>    contig is UCSC transcript ID, how can I change this to gene symbol or
>    ensemble gene ID?
>
> You need the annotation file, e.g. the GTF file, where you have the link
between transcript IDs and gene IDs. Ensembl provides a GTF with that info.
I don't know if the UCSC annotation provides that.

>
>    1. In the output file, I see only contig and position. What does this
>    mean? Is there any way of getting the chrosome as well in the output file?
>
> The "Contig" in this case is the reference sequence used for the m6A
detection, which is the transcript ID. If you have a GTF file, you can
transfer the transcript positions to chromosomal positions with our R2DTools
https://github.com/comprna/R2Dtool


>
>    1. What is the well-acceptable threshold to identify a significant
>    m6A-modified site based on probability and stoichiometry?
>
> We describe in our preprint a permutation approach to establish
empirically a cut off for the Model 2 probability. The script is here:
https://github.com/comprna/CHEUI/blob/master/scripts/CHEUI-solo_permutate.py


What this does is shuffle all individual read probabilities around,
maintaining the coverage per site, and rerun Model 2. The results will help
you establish an FDR estimate at every possible probability cutoff.

In the preprint we chose P>0.9999 as this indicated an FDR of ~0.

>
>    1. I beg pardon as some questions are not relevant to CHEUI.
>
>
No problem. They are all relevant.
Thanks for all the questions

I hope this helps

Eduardo

**Comment by rezarahman12** [comment]
Dear Eduardo,
Thank you so much for your quick responses and nice clarifications on my issues. I truly appreciate your time and consideration. Best regards
Reza
