### ISSUE TITLE
multi-threading in running model 1

### ISSUE THREAD

**Issue by rezarahman12** [comprna/CHEUI#21]
Hi CHEUI team,

I'm running the below cheui script for almost 24 hours with 28 CPU in HPC, however, it seems slow. Is there any way to specify CPU core as we can do in CHEUI preprocessing steps?

python /scratch/qbi/uqmrah19/CHEUI/scripts/CHEUI_predict_model1.py \
-i /scratch/qbi/uqmrah19/CHEUI/cheui/ONT_Reza/cheui_analysis/ctrl1/out_A_signals+IDs.p/eventalign_signals+IDS.p \
-m /scratch/qbi/uqmrah19/CHEUI/CHEUI_trained_models/CHEUI_m6A_model1.h5 \
-o ./read_level_m6A_predictions_WT_rep1.txt \
-l WT_rep1

I appreciate your time.

Best regards
Reza

**Comment by pre-mRNA** [comment]
It's a lot faster to do the model 1 predictions with GPU available.

However, if you want to predict with CPU, you can split the eventalign file, preprocess the chunks in parallel, and perform the model 1 prediction with 1 core each. 

E.g., using [xSplit](https://github.com/pre-mRNA/xSplit): 

```
events="/path/to/nanopolish.tsv"

# split the nanopolish file into 100 chunks, keeping read_ids (col4) intact between chunks
cat ${events} | xSplit -n 100 -p "./${sample_name}_events_split_" -c 4 

# use gnu parallel to preprocess the chunks 
ls "*_events_split_*" | parallel -j 104 '/CHEUI_preprocess_m6A.py -i {} -m '"$model"' -o '"$out_dir"' -s {/.} -n 1'

# similarly, predict model 1 in parallel
```

You will need to merge and sort the model 1 files before predicting site-level modification using model 2.
