### ISSUE TITLE
Regarding output of the m6A probability and stoichiometry command

### ISSUE THREAD

**Issue by Proy321** [comprna/CHEUI#22]
I was trying to execute the following command for the prediction of m6A probability and stoichiometry at every A nucleotide site in the reference transcriptome  y using following command, but unfortunately the command executed with error(attached herewith). I need help regarding the same.

![Screenshot (33)](https://github.com/comprna/CHEUI/assets/140142819/61952fb2-9494-4577-8f81-91fb642aef98)
![Screenshot (32)](https://github.com/comprna/CHEUI/assets/140142819/520a3122-2d9e-4b1b-aa41-d183fd14c664)

**python3 ../scripts/CHEUI_predict_model2.py -i read_level_m6A_predictions_sorted.txt -m  ../CHEUI_trained_models/CHEUI_m6A_model2.h5 -o site_level_m6A_predictions.txt**

**Comment by EduEyras** [comment]
Hi,

Thanks for your message.

Could you please send us a copy of your command line?

Thanks

Eduardo

**Comment by EduEyras** [comment]
Sorry, I just saw it at the bottom of the page

*python3 ../scripts/CHEUI_predict_model2.py -i
read_level_m6A_predictions_sorted.txt -m
../CHEUI_trained_models/CHEUI_m6A_model2.h5 -o
site_level_m6A_predictions.txt*

The command looks ok to me.
There seems to be an issue with your system not finding keras?
Perhaps Akanksha might be able to help

Thanks

Eduardo

**Comment by Proy321** [comment]
It would be nice if Akansha can guide me regarding the same.
