### ISSUE TITLE
Regarding CHEUI tool

### ISSUE THREAD

**Issue by Proy321** [comprna/CHEUI#25]
Hi,
I have a small query regarding the tool, can I use the genomic fasta file as a reference instead of transcriptomic fasta file for detection of methylation events.
Looking forward to hearing from you.

Thanks

**Comment by EduEyras** [comment]
This is possible. AJ (cc'ed) has been working on that. He can mention
whether there is a pipeline ready for that.
best

E.

**Comment by pre-mRNA** [comment]
Hi,

This is something we are actively working on. 

CHEUI's depends on plus-strand alignments, so aligning to transcript sequences directly is a good strategy. However, we have developed a workaround to still use CHEUI with genomic alignments. To do so, we align reads to the plus-strand of the genome, and additionally, to the rev/comp'ed minus strand of the genome, such that all alignments are plus-stranded, even though we are aligning to genome sequences. 

The following [experimental python script](https://github.com/pre-mRNA/CHEUI/blob/master/scripts/transpose-to-plus-strand.py) can be used to transpose genomic alignments on both strands to plus-stranded only. 

The script depends on biopython and pysam packages. The script takes as input a BAM file of genomic alignments, and the corresponding reference FASTA file. The outputs include (1) file of transposed, plus-stranded only genome alignments, along with (2) the plus-strand only FASTA file, (required as a reference by nanopolish during the eventalign step), and finally (3) a GTF file which can be [used by R2Dtool](https://github.com/comprna/R2Dtool/tree/main) to transpose the sites back to their original (i.e. plus and minus) stranded genomic alignments. 

Example usage: 

python ./transpose-to-plus-strand.py ./input.bam ./input.fasta ./output.fasta ./output.gtf ./output_merged.bam

The default minimap2 parameters are '-a -x splice -k 15 --for-only', but you can change them using optional flag --minimap_params "params". Remember to use the --for-only flag. 

Let me know if you have any feedback.

**Comment by Proy321** [comment]
Thanks for your response.
The objective that I am working on is on detection of methylation events on lncRNA using the CHEUI tool. I have reads from direct RNA Sequencing(SQK-RNA002), so how can I separate out sense and antisense reads from the raw reads and further identify methylation events from them, as I want to identify modifications in both sense and antisense RNA.
I beg pardon, as the questions I am raising are not relevant to CHEUI.

I would appreciate your time and help.

Thanks & Regards
Priyanka Roy

**Comment by pre-mRNA** [comment]
You should be able to align your reads to the gene using minimap2 and subsequently transpose then to the plus strand using the script I shared. The script preserves original sense/antisense information, e.g. for a a gene on the plus strand, sense reads will be mapped to the original plus strand, and antisense reads will be mapped to the reverse-transcribed minus strand. This should probably work for your use case.

**Comment by Proy321** [comment]
Thanks for your response.
For aligning the antisense reads, can I do the reverse complementary of the plus strand of the reference genome and then use the minimap, so that I can separate out the antisense reads.
I would appreciate your time and help.

Thanks & Regards
Priyanka Roy

**Comment by pre-mRNA** [comment]
You could try first aligning to the genome using a command like 'minimap2 -a -x splice', which will by default align the reads in a stranded manner, and will separate your sense and antisense reads. Then, you can transpose the reads using the script I shared; reads aligned to the genome plus strand will remain on the plus strand, whereas reads aligned to the minus strand will be re-aligned to a reverse-transposed minus strand (i.e. they will also be aligned to the plus strand). This should be compatible with CHEUI.
