### ISSUE TITLE
Low m5C modification site number overlapped with m5c-atlas database

### ISSUE THREAD

**Issue by baishengjun** [comprna/CHEUI#28]
Hi,

I obtained around 22,000 m5C midification sites using CHEUI-solo model, and I overlapped it with m5C-atlas database, only 1786 overlapped site obtained.
I wonder how can I adjust parmeters to get high overlapped site? or any tips should I attention ?

Thanks a lot,
Bai

**Comment by EduEyras** [comment]
Hi Bai,

Did you use any cut-off for the probability? You can change that to get
more predictions.

I hope this helps

Eduardo
