### ISSUE TITLE
Regarding prediction of stoichiometry

### ISSUE THREAD

**Issue by PRIYANKA-22091995** [comprna/CHEUI#30]
Hello Team,

I have basic question regarding the stoichiometry, if i just consider the probability threshold above 0.9 in the **probability column** of 'site-level prediction file ' without considering any threshold for stoichiometry, is that accurate way to analyze the data or if i consider the **stoichiometry threshold above 0.7** and **probability threshold above 0.9**, which is more accurate way to analyze the data. It would be nice to have your inputs on the same.
Looking forward to your reply.

Thanks & Regards
Priyanka Roy

**Comment by pre-mRNA** [comment]
We tend to filter for model II sites with high probability (that the site is modified at all) and stoichiometry over a given cutoff. 
This allows us to control the false positive rate for modification detection.
