### ISSUE TITLE
Do CHEUI models work on Bacterial RNA modification detection?

### ISSUE THREAD

**Issue by abcdtree** [comprna/CHEUI#31]
Hi Dear CHEUI developers,

Thank you so much for creating this magical tool to detect RNA modifications.

I would like to ask whether CHEUI models work on Human only or it might work on Bacteria too? 

Thanks,

Josh

**Comment by EduEyras** [comment]
Hi Josh,

Thanks a lot for your enthusiasm!

They do work indeed! We are applying the CHEUI models to many species,
including bacteria.

Please let us know how it goes with it

best

Eduardo
