### ISSUE TITLE
Do CHEUI models work on SARS-CoV-2 RNA modification detection? 

### ISSUE THREAD

**Issue by kir1to455** [comprna/CHEUI#34]
Hi,
Thank you for developing this tool.
I would like to know if the CHEUI model can be applied to SARS-CoV-2?
I have obtained the result of solo outputs using CHEUI.
But almost all probability values are 0.013649046.
![image](https://github.com/comprna/CHEUI/assets/87375686/44959429-bf53-4ea2-846c-62f030aaab6d)
Only one DRACH site with probability 0.99999905.
![image](https://github.com/comprna/CHEUI/assets/87375686/e305c678-d853-485a-99b3-21d4723a9d9a)
In addition, I also have samples with Mettle3 inhibitors. Can I use CHEUI diff to detect the differences between the two samples?
Could someone give me some advice?

Best wishes,
Kirito

**Comment by EduEyras** [comment]
Hi Kirito,

Yes, you can use CHEUI for whatever organism and RNA

We're using it systematically across all kingdoms of life

Yes, you can also use CHEUI-diff to compare between both conditions.

Those to A sites with high probability are encouraging.

CHEUI predicts in all sequence contexts, so the non-DRACH AGATG modified
site could be m6A, or other type of adenosine methylation. We saw that
nanopore does not distinguish well between m6A and m1A.

I hope this helps

Eduardo
