### ISSUE TITLE
Compatibility with the new direct RNA seq kit

### ISSUE THREAD

**Issue by panagi0tis90** [comprna/CHEUI#36]
Dear authors,
Could cheui be used to identify modifications in datasets derived from the new ONT kit SQK-RNA004, or it is only compatible with 002?

Thanks in advance!
Pan

**Comment by EduEyras** [comment]
Hi Pan,

We have new models for the R004 data. We are hoping to make them available
soon

Thanks

Eduardo

**Comment by wdecoster** [comment]
Hi Eduardo,

Do you have an update on the RNA004 models?

Thanks,
Wouter
