### ISSUE TITLE
Question about preprocessing

### ISSUE THREAD

**Issue by doshirLV** [comprna/CHEUI#40]
Hello CHEUI developers,

I was wondering if `.fastq` files from base-calling should be combined prior to alignment and resquiggling, should I keep them separate, or does it not matter? 

I appreciate your attention regarding this,
Raj

**Comment by doshirLV** [comment]
Also, a suggestion for your documentation:

In the alignment command, samtools sort is not piped with samtools view and minimap2 so it must be done manually prior to indexing. No worries about this but I just thought I would let you know.

Best,
Raj

**Comment by pre-mRNA** [comment]
> Hello CHEUI developers,
> 
> I was wondering if `.fastq` files from base-calling should be combined prior to alignment and resquiggling, should I keep them separate, or does it not matter?
> 
> I appreciate your attention regarding this, Raj

Yes, I'd suggesting combining the fastq files using ```cat``` before alignment.

**Comment by pre-mRNA** [comment]
> Also, a suggestion for your documentation:
> 
> In the alignment command, samtools sort is not piped with samtools view and minimap2 so it must be done manually prior to indexing. No worries about this but I just thought I would let you know.
> 
> Best, Raj

Thanks for catching this, I've updated it in the README
