### ISSUE TITLE
Cheui-solo, invalid syntax of eventalign.txt input file

### ISSUE THREAD

**Issue by BrendanBeahan** [comprna/CHEUI#41]
Hello,

I built a singularity image utilizing the dependencies you specified for Cheui, and then attempted to run cheui-solo via the following:

`singularity exec Cheui/cheui_image.sif python /WT/Mus_Musculus_WT/nanopolish/transcriptome/eventalign_readName.txt -m CHEUI_trained_models/CHEUI_m6A_model2.h5 -o /WT/Mus_Musculus_WT/nanopolish/transcriptome/out_A_signals+IDs.p`

However, I was presented with the following error:

```
File "/WT/Mus_Musculus_WT/nanopolish/transcriptome/eventalign_readName.txt", line 1
    contig      position        reference_kmer  read_name       strand  event_index     event_level_mean        event_stdv      event_length    model_kmer      model_mean model_stdv       standardized_level      start_idx       end_idx samples
                                                                                                                                                                                                   ^
SyntaxError: invalid syntax
```

It appears there is an issue with the standardized_level. I wonder if perhaps I need to change the way that I generate my initial eventalign file? I thought it conformed to what was required, but this is what I run to generate them currently:

```
		/usr/bin/nanopolish/nanopolish index -d ${params.resultsDir}/${condition}/${sample}/FAST5/ ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq

		/usr/bin/nanopolish/nanopolish eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam --genome transcriptome.fa --samples --signal-index --scale-events -n --summary ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/summary.txt --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/eventalign_readName.txt

		/usr/bin/nanopolish/nanopolish eventalign --reads ${params.resultsDir}/${condition}/${sample}/FASTQ/singleReadsFASTQ.fastq --bam ${params.resultsDir}/${condition}/${sample}/transcriptomeAlignment/minimap.filt.sort.bam --genome transcriptome.fa --signal-index --scale-events --summary ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/summary.txt --threads ${task.cpus} > ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/eventalign_readIndex.txt


```

With the results from ${params.resultsDir}/${condition}/${sample}/nanopolish/transcriptome/eventalign_readName.txt being what I use for my input into cheui solo.

I feel like I'm missing something obvious, and if you had any insights into what I'm doing wrong I'd appreciate it!

**Comment by pre-mRNA** [comment]
Hi, could you please run nanopolish without the '--signal-index' flag or exclude the signal index columns from your file using awk? CHEUI does not expect those columns.

**Comment by BrendanBeahan** [comment]
Perhaps my most embarrassing github issue! I was simply missing the preprocess.py command..
