### ISSUE TITLE
Reads ID non unique in read level result

### ISSUE THREAD

**Issue by abcdtree** [comprna/CHEUI#42]
Hi Dear author,

I recently found that in the result after predicting model 1 (read level result), there are some duplicate reads ID in the result as below:

```
20230917_11775_control_read_level_m6A_predictions.txt.gz:ATCC11775_23S_rRNA_1609_CGACACAGG_e381e2b5-ddd0-44df-a773-ba4819f48419	0.8965372	WT_20230917_11775_control
20230917_11775_control_read_level_m6A_predictions.txt.gz:ATCC11775_23S_rRNA_1609_CGACACAGG_e381e2b5-ddd0-44df-a773-ba4819f48419	0.17455584	WT_20230917_11775_control
```

They have the same reads ID, but different probability of modification. I checked the fastq and there is no duplicate ID in fastq. However, in the bam file, there are secondary mapping. Is that the reason there are duplicate reads ID in the read level prediction result?

**Comment by pre-mRNA** [comment]
Hi, 

We suggest filtering the BAM for the best alignment for each read, prior to running eventalign and CHEUI. 

You can use the following command to filter the BAM for the primary alignment for each read:

```
samtools view -F 2324 -b 
```

The duplicated predictions are likely due to secondary alignments in your BAM file.
