### ISSUE TITLE
What's the difference between m6A stoichiometry and probability?

### ISSUE THREAD

**Issue by WeipengMO** [comprna/CHEUI#8]
Hi developer,

Thank you for developing such an excellent tool. I am new to m6A RNA modification. Could you tell me what's the difference between stoichiometry and modification probability for m6A (or m5C) in output files for CHEUI models?

Thank you in advance,
Weipeng

**Comment by EduEyras** [comment]
Thank you Weipeng for your email

The modification probability is the probability that the transcriptomic
site can be considered modified given the evidence

Stoichiometry is the proportion of reads that cover that site and have that
nucleotide modified. It represents the proportion of copies of molecules in
the cell that has that site modified.

I hope this clarifies it

best

Eduardo

**Comment by WeipengMO** [comment]
I get it. Thank you for your reply, Eduardo.
